### ISSUE TITLE
Blank spaces between items 

### ISSUE THREAD

**Issue by htooaungkyaw** [saket/InboxRecyclerView#13] opened 2018-10-12 11:28 UTC
We see blank spaces between items once we open the detail and back to list. Blank space is equally in size with item and consequently make the below items overlapping each other.

**Comment by saket** [comment] 2018-10-12 17:13
Can you help me reproduce this? A sample usage and a screen recording will be useful.

**Comment by saket** [comment] 2018-10-21 13:50
Closing this due to inactivity. Please feel free to re-open this.

**Comment by charlie-niekirk** [comment] 2019-03-04 20:21
I'm now getting this issue, it happens the first time you open and then close an expandable item.  Subsequent opening/closing of items seems to fix the issue (except for the first item).  From what it looks like, the viewbounds of the items are being changed so that there is blank space being drawn above their original bounds (which overlays the items above).

I'll try get a recording for you.

**Comment by saket** [comment] 2019-03-06 07:34
Is this related to #26?

**Comment by charlie-niekirk** [comment] 2019-03-06 17:07
Yes, sorry it was.  I managed to fix this specific issue.  However, after I open an expandable page and then collapse it again, the recyclerview item immediately below the opened item doesn't animate up to the correct position (it seems it's about 1 or 2dp below where it is meant to be).  You can see this in the video below as after the collapse, the spacing under the expanded item is slightly larger:

https://vimeo.com/321789522

**Comment by saket** [comment] 2019-07-30 02:41
Closing this as a duplicate of #27

**Closed as completed by saket** 2019-07-30 02:41 UTC
